version: '3'

services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

    nestjs:
        build: .
        container_name: nestjs
        ports:
            - 3000:3000
        environment:            
            DATABASE: mongodb://mongodb:27017/limechain-intro
        depends_on:
            - mongodb                

volumes:
    mongodb: {}
